{"timestamp": "2025-02-11T23:48:09.871620", "level": "INFO", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Incoming request", "context": {"correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "method": "POST", "url": "http://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev/projects", "client_host": "172.31.128.11", "headers": {"host": "6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0", "content-length": "157", "accept": "application/json", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9", "content-type": "application/json", "origin": "https://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev", "referer": "https://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev/docs", "sec-ch-ua": "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "sec-fetch-dest": "empty", "sec-fetch-mode": "cors", "sec-fetch-site": "same-origin", "x-forwarded-for": "67.11.111.13, 165.225.36.171, 10.83.1.32", "x-forwarded-proto": "https", "x-replit-user-bio": "", "x-replit-user-id": "", "x-replit-user-name": "", "x-replit-user-profile-image": "", "x-replit-user-roles": "", "x-replit-user-teams": "", "x-replit-user-url": ""}, "path_params": {}, "query_params": {}, "request_id": null, "path": "/projects"}}
{"timestamp": "2025-02-11T23:48:09.873605", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Database session created", "context": {}}
{"timestamp": "2025-02-11T23:48:09.876943", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "ProjectRepository initialized", "context": {}}
{"timestamp": "2025-02-11T23:48:09.877162", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "ProjectService initialized with database session", "context": {}}
{"timestamp": "2025-02-11T23:48:09.877374", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Starting creation of project with data: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active'}", "context": {}}
{"timestamp": "2025-02-11T23:48:10.299654", "level": "INFO", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Created default project manager: Unassigned", "context": {}}
{"timestamp": "2025-02-11T23:48:10.322364", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Found existing customer: Unassigned", "context": {}}
{"timestamp": "2025-02-11T23:48:10.322758", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Fetching project with ID: Project2", "context": {}}
{"timestamp": "2025-02-11T23:48:10.345440", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Creating new project with data: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active'}", "context": {}}
{"timestamp": "2025-02-11T23:48:10.345788", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Creating new project with data: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active'}", "context": {}}
{"timestamp": "2025-02-11T23:48:10.345970", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Fetching project with ID: Project2", "context": {}}
{"timestamp": "2025-02-11T23:48:10.409825", "level": "ERROR", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Error creating project: (psycopg2.errors.ForeignKeyViolation) insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n[SQL: INSERT INTO projects (project_id, name, description, customer, project_manager, status, created_at, updated_at) VALUES (%(project_id)s, %(name)s, %(description)s, %(customer)s, %(project_manager)s, %(status)s, %(created_at)s, %(updated_at)s) RETURNING projects.id]\n[parameters: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active', 'created_at': datetime.datetime(2025, 2, 11, 23, 48, 10, 366536), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)", "context": {}}
{"timestamp": "2025-02-11T23:48:10.410234", "level": "ERROR", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Error creating project: (psycopg2.errors.ForeignKeyViolation) insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n[SQL: INSERT INTO projects (project_id, name, description, customer, project_manager, status, created_at, updated_at) VALUES (%(project_id)s, %(name)s, %(description)s, %(customer)s, %(project_manager)s, %(status)s, %(created_at)s, %(updated_at)s) RETURNING projects.id]\n[parameters: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active', 'created_at': datetime.datetime(2025, 2, 11, 23, 48, 10, 366536), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)", "context": {}}
{"timestamp": "2025-02-11T23:48:10.412067", "level": "ERROR", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Database session error: (psycopg2.errors.ForeignKeyViolation) insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n[SQL: INSERT INTO projects (project_id, name, description, customer, project_manager, status, created_at, updated_at) VALUES (%(project_id)s, %(name)s, %(description)s, %(customer)s, %(project_manager)s, %(status)s, %(created_at)s, %(updated_at)s) RETURNING projects.id]\n[parameters: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active', 'created_at': datetime.datetime(2025, 2, 11, 23, 48, 10, 366536), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)", "context": {}}
{"timestamp": "2025-02-11T23:48:10.420438", "level": "ERROR", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Database session error details:", "context": {}, "exception": "Traceback (most recent call last):\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/workspace/database/database.py\", line 113, in get_db\n    yield db\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/fastapi/concurrency.py\", line 27, in contextmanager_in_threadpool\n    yield await run_in_threadpool(cm.__enter__)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/fastapi/routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/fastapi/routing.py\", line 214, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/concurrency.py\", line 39, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2505, in run_sync_in_worker_thread\n    return await future\n           ^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 1005, in run\n    result = context.run(func, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/main.py\", line 144, in create_project\n    return service.create_project(project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/services/project_service.py\", line 102, in create_project\n    created_project = self.project_repo.create(self.db, project_data)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/database/project_repository.py\", line 41, in create\n    db.commit()\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 2028, in commit\n    trans.commit(_to_root=True)\n  File \"<string>\", line 2, in commit\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 1313, in commit\n    self._prepare_impl()\n  File \"<string>\", line 2, in _prepare_impl\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 1288, in _prepare_impl\n    self.session.flush()\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 4352, in flush\n    self._flush(objects)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 4487, in _flush\n    with util.safe_reraise():\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 4448, in _flush\n    flush_context.execute()\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py\", line 466, in execute\n    rec.execute(self)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py\", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py\", line 93, in save_obj\n    _emit_insert_statements(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py\", line 1233, in _emit_insert_statements\n    result = connection.execute(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1418, in execute\n    return meth(\n           ^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/sql/elements.py\", line 515, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1640, in _execute_clauseelement\n    ret = self._execute_context(\n          ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1846, in _execute_context\n    return self._exec_single_context(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1986, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 2355, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n[SQL: INSERT INTO projects (project_id, name, description, customer, project_manager, status, created_at, updated_at) VALUES (%(project_id)s, %(name)s, %(description)s, %(customer)s, %(project_manager)s, %(status)s, %(created_at)s, %(updated_at)s) RETURNING projects.id]\n[parameters: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active', 'created_at': datetime.datetime(2025, 2, 11, 23, 48, 10, 366536), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)"}
{"timestamp": "2025-02-11T23:48:10.422406", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Database session closed", "context": {}}
{"timestamp": "2025-02-11T23:48:10.425917", "level": "ERROR", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Request failed with exception", "context": {"correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "error_type": "IntegrityError", "error_message": "(psycopg2.errors.ForeignKeyViolation) insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n[SQL: INSERT INTO projects (project_id, name, description, customer, project_manager, status, created_at, updated_at) VALUES (%(project_id)s, %(name)s, %(description)s, %(customer)s, %(project_manager)s, %(status)s, %(created_at)s, %(updated_at)s) RETURNING projects.id]\n[parameters: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active', 'created_at': datetime.datetime(2025, 2, 11, 23, 48, 10, 366536), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)", "traceback": "Traceback (most recent call last):\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/workspace/utils/middleware.py\", line 45, in logging_middleware\n    response = await call_next(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/middleware/base.py\", line 163, in call_next\n    raise app_exc\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/middleware/base.py\", line 149, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/middleware/cors.py\", line 93, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/middleware/cors.py\", line 144, in simple_response\n    await self.app(scope, receive, send)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/routing.py\", line 715, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/routing.py\", line 735, in app\n    await route.handle(scope, receive, send)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/fastapi/routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/fastapi/routing.py\", line 214, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/starlette/concurrency.py\", line 39, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2505, in run_sync_in_worker_thread\n    return await future\n           ^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 1005, in run\n    result = context.run(func, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/main.py\", line 144, in create_project\n    return service.create_project(project)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/services/project_service.py\", line 102, in create_project\n    created_project = self.project_repo.create(self.db, project_data)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/database/project_repository.py\", line 41, in create\n    db.commit()\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 2028, in commit\n    trans.commit(_to_root=True)\n  File \"<string>\", line 2, in commit\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 1313, in commit\n    self._prepare_impl()\n  File \"<string>\", line 2, in _prepare_impl\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py\", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n                ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 1288, in _prepare_impl\n    self.session.flush()\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 4352, in flush\n    self._flush(objects)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 4487, in _flush\n    with util.safe_reraise():\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 4448, in _flush\n    flush_context.execute()\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py\", line 466, in execute\n    rec.execute(self)\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py\", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py\", line 93, in save_obj\n    _emit_insert_statements(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py\", line 1233, in _emit_insert_statements\n    result = connection.execute(\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1418, in execute\n    return meth(\n           ^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/sql/elements.py\", line 515, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1640, in _execute_clauseelement\n    ret = self._execute_context(\n          ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1846, in _execute_context\n    return self._exec_single_context(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1986, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 2355, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table \"projects\" violates foreign key constraint \"projects_project_manager_fkey\"\nDETAIL:  Key (project_manager)=(-) is not present in table \"project_managers\".\n\n[SQL: INSERT INTO projects (project_id, name, description, customer, project_manager, status, created_at, updated_at) VALUES (%(project_id)s, %(name)s, %(description)s, %(customer)s, %(project_manager)s, %(status)s, %(created_at)s, %(updated_at)s) RETURNING projects.id]\n[parameters: {'project_id': 'Project2', 'name': 'Project2', 'description': 'Project2', 'customer': 'Unassigned', 'project_manager': '-', 'status': 'active', 'created_at': datetime.datetime(2025, 2, 11, 23, 48, 10, 366536), 'updated_at': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n", "request_method": "POST", "request_url": "http://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev/projects", "request_headers": {"host": "6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0", "content-length": "157", "accept": "application/json", "accept-encoding": "gzip, deflate, br, zstd", "accept-language": "en-US,en;q=0.9", "content-type": "application/json", "origin": "https://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev", "referer": "https://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev/docs", "sec-ch-ua": "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Microsoft Edge\";v=\"132\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "sec-fetch-dest": "empty", "sec-fetch-mode": "cors", "sec-fetch-site": "same-origin", "x-forwarded-for": "67.11.111.13, 165.225.36.171, 10.83.1.32", "x-forwarded-proto": "https", "x-replit-user-bio": "", "x-replit-user-id": "", "x-replit-user-name": "", "x-replit-user-profile-image": "", "x-replit-user-roles": "", "x-replit-user-teams": "", "x-replit-user-url": ""}, "client_host": "172.31.128.11", "query_params": {}, "path_params": {}, "path": "/projects", "origin": "https://6ed7ce35-85b3-498b-9e9b-4d63631ed8e3-00-2owzgyvztotfg.worf.replit.dev", "cors_method": null, "cors_headers": null}}
{"timestamp": "2025-02-11T23:48:10.426773", "level": "DEBUG", "correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "logger": "TimesheetTracker", "message": "Adding CORS headers to response", "context": {"correlation_id": "0246b388-ef5c-45a0-8a21-be5b041fc573", "method": "POST", "path": "/projects", "status_code": 500}}
INFO:     172.31.128.11:46190 - "POST /projects HTTP/1.1" 500 Internal Server Error